### ISSUE TITLE
Add the possibility to configure custom headers globally

### ISSUE THREAD

**Issue by neslinesli93** [primait/bridge_ex#33]
So far, this library allows to specify two global configuration params:
- `log_query_on_error`
- `log_response_on_error`

It would be nice to have the possibility to specify custom headers to be used on every bridge. For example, we've been using the pattern of adding the service' name in a custom header, which is particularly useful when grepping calls in load balancer logs (i know there is opentelemetry for this, but our current retention time and filtering features are not on par with the ELK stack)

**Comment by andreapavoni** [comment]
it actually lets you to configure custom headers on single bridges, however you can set a global config, then refer to it when defining the bridge. Yes, it's bit more verbose (and repetitive), but it's also more explicit and declarative.

considering the nature of this library (exposing helpers to build bridges for several endpoints), I suspect that making a config like that as implicit might be more error prone.

IMHO, having global configs for logging makes sense, but I'd avoid the same approach for headers to use in bridge.

**Comment by neslinesli93** [comment]
> it actually lets you to configure custom headers on single bridges, however you can set a global config, then refer to it when defining the bridge. Yes, it's bit more verbose (and repetitive), but it's also more explicit and declarative.
> 
> considering the nature of this library (exposing helpers to build bridges for several endpoints), I suspect that making a config like that as implicit might be more error prone.
> 
> IMHO, having global configs for logging makes sense, but I'd avoid the same approach for headers to use in bridge.

sorry, i completely missed your reply... fair enough for me, you are right :+1:
