### ISSUE TITLE
endpoint option is expected at compile time

### ISSUE THREAD

**Issue by chess4ever** [primait/bridge_ex#81]
During a refactor of configurations in an elixir project, I have found out that the `endpoint` option is a required option of the `use BridgeEx.Graphql` expression, so it is expected at compile time.
This is a problem for projects that are configuring this option at runtime in runtime.exs.
I see two possible solutions that should keep the api backward compatible:
1. injecting a behaviour though the `use` macro to enforce the implementation of an `endpoint` function in the client module, and use that function instead of the currently used module attribute (which is defined by the `use` macro)
2. give the possibilty to pass the `endpoint` value in the option parameter (already present, currently used for headers among other things)

**Comment by cpiemontese** [comment]
Could this be solved by #78?

**Comment by mbusi** [comment]
Yeah I linked them :)
